# modules/utils/language.py
"""Language management with translations"""

import json


class LanguageManager:
    """Manage translations and language switching"""
    
    def __init__(self):
        self.translations = {
            'English': {
                'title': 'Center of Mass & Centroid Analysis System',
                'subtitle': '2D and 3D Geometry Analysis Platform',
                'welcome': 'Welcome to COM Analysis System',
                '2d_analysis': '2D Analysis',
                '3d_analysis': '3D Analysis',
                'stl_import': 'STL Import',
                'report_generator': 'Report Generator',
                'settings': 'Settings',
                'calculate': 'Calculate',
                'reset': 'Reset',
                'export_pdf': 'Export PDF',
                'export_csv': 'Export CSV',
                'quick_start_guide': 'Quick Start Guide',
                'quick_start_steps': '''
                    1. **Choose Analysis Type**: Select 2D or 3D analysis from the sidebar
                    2. **Input Geometry**: Enter dimensions or import files
                    3. **Calculate**: Click calculate to get results
                    4. **Visualize**: Interact with real-time 3D visualization
                    5. **Export**: Generate PDF reports or export data
                ''',
                'btn_2d_title': '🔷\n\n**2D Analysis**',
                'btn_2d_desc': 'Calculate centroids for 2D shapes',
                'btn_2d_list': '• Analytical formulas\n• Composite shapes\n• Coordinate input\n• Area calculation',
                'btn_3d_title': '🔶\n\n**3D Analysis**',
                'btn_3d_desc': 'Compute center of mass for 3D solids',
                'btn_3d_list': '• Cube, sphere, cylinder\n• Composite bodies\n• Volume calculation\n• 3D visualization',
                'btn_stl_title': '🔧\n\n**STL Import**',
                'btn_stl_desc': 'Import and analyze 3D mesh geometries',
                'btn_stl_list': '• Mesh processing\n• Volume integration\n• Centroid calculation\n• Mesh statistics',
                # Navigation
                'nav_home': 'Home',
                'nav_2d': '2D Analysis',
                'nav_3d': '3D Analysis',
                'nav_stl': 'STL Import',
                'nav_report': 'Report Generator',
                'nav_settings': 'Settings',
                'nav_label': 'Navigation',
                # Theme & Language
                'theme': 'Theme',
                'theme_dark': 'Dark',
                'theme_light': 'Light',
                'theme_system': 'System',
                'language_label': 'Language / زبان',
                'lang_english': 'English',
                'lang_persian': 'Persian',
                # Input modes
                'input_mode': 'Input Mode',
                'simple_shapes': 'Simple Shapes',
                'composite_geometry': 'Composite Geometry',
                'coordinate_input': 'Coordinate Input',
                # Shape types
                'shape_type': 'Shape Type',
                'rectangle': 'Rectangle',
                'circle': 'Circle',
                'triangle': 'Triangle',
                'polygon': 'Polygon',
                'cube': 'Cube',
                'box': 'Box',
                'sphere': 'Sphere',
                'cylinder': 'Cylinder',
                'cone': 'Cone',
                'pyramid': 'Pyramid',
                # Dimensions
                'width': 'Width',
                'height': 'Height',
                'length': 'Length',
                'radius': 'Radius',
                'base': 'Base',
                'base_length': 'Base Length',
                'base_width': 'Base Width',
                'base_radius': 'Base Radius',
                'center_x': 'Center X',
                'center_y': 'Center Y',
                'position_x': 'Position X',
                'position_y': 'Position Y',
                'position_z': 'Position Z',
                # Operations
                'operation': 'Operation',
                'add_material': '🟢 Add Material',
                'cut_hole': '🔴 Cut Hole',
                'add_component': '➕ Add Component',
                'add_3d_component': '➕ Add 3D Component',
                'add_btn': '➕ Add',
                'cut_btn': '🔴 Cut',
                # Composite
                'composite_shape_builder': 'Composite Shape Builder',
                'composite_3d_builder': '3D Composite Builder',
                'components_table': 'Components Table',
                'components_3d_table': '3D Components Table',
                'click_to_select': 'Click a row to select, then press delete:',
                'delete_selected': '🗑️ Delete Selected',
                'selected_info': 'Selected',
                'current_components': 'Current Components',
                'remove': 'Remove',
                # Preview & Results
                'live_preview': 'Live Preview',
                'live_preview_3d': 'Live Preview (3D Composite)',
                'area': 'Area',
                'volume': 'Volume',
                'net_area': 'Net Area',
                'net_volume': 'Net Volume',
                'centroid_x': 'Centroid X',
                'centroid_y': 'Centroid Y',
                'centroid_z': 'Centroid Z',
                'total_area': 'Total Area',
                # Stability
                'stability_analysis': 'Stability Analysis',
                'stability': 'Stability',
                'stable': 'Stable',
                'potentially_unstable': 'Potentially Unstable',
                'stability_status': 'Stability Status',
                'centroid_height': 'Centroid height',
                'stability_stable_msg': 'This is within the support base, indicating stability.',
                'stability_unstable_msg': 'The high center of mass may cause instability.',
                # Polygon input
                'polygon_coordinate_input': 'Polygon Coordinate Input',
                'input_method': 'Input Method',
                'manual_entry': 'Manual Entry',
                'csv_upload': 'CSV Upload',
                'enter_coordinates': 'Enter coordinates (one per line: x,y)',
                'invalid_coordinate': 'Invalid coordinate format',
                'need_3_coordinates': 'Please enter at least 3 coordinates',
                'upload_csv': 'Upload CSV file',
                # STL
                'upload_stl': 'Upload STL File',
                'vertices': 'Vertices',
                'faces': 'Faces',
                'error_stl': 'Error processing STL file',
                # Buttons
                'save_to_report': '💾 Save to Report',
                'generate_report': 'Generate Report',
                'download_pdf': 'Download PDF',
                'download_json': 'Download JSON',
                'download_csv': 'Download CSV',
                'reset_shape': '🔄 Reset Shape',
                'reset_all': '🔄 Reset All',
                'reset_btn': '🔄 Reset',
                'save_settings': 'Save Settings',
                # Report Generator
                'analysis_available': 'Analysis data available for report generation',
                'no_analysis_data': 'No analysis data available. Please perform an analysis first.',
                'preview_image_label': 'Preview Image (will be included in report)',
                'project_name': 'Project Name',
                'engineer_name': 'Engineer Name',
                'additional_notes': 'Additional Notes',
                'report_format': 'Report Format',
                'generating_report': 'Generating report...',
                'results_saved': 'Results saved! Go to Report Generator to export.',
                'settings_saved': 'Settings saved successfully!',
                # Settings
                'unit_system': 'Unit System',
                'length_unit': 'Length Unit',
                'precision': 'Precision',
                'decimal_places': 'Decimal Places',
                'visualization_settings': 'Visualization Settings',
                'show_grid': 'Show Grid',
                'show_axes': 'Show Axes',
                'marker_size': 'Marker Size',
                # Units
                'mm': 'mm',
                'cm': 'cm',
                'm': 'm',
                'in': 'in',
                'mm2': 'mm²',
                'mm3': 'mm³',
                # Report PDF labels
                'report_title': 'Geometry Preview',
                'report_analysis_results': 'Analysis Results',
                'report_parameter': 'Parameter',
                'report_value': 'Value',
                'report_unit': 'Unit',
                'report_notes': 'Additional Notes',
                'report_generated_by': 'Generated by Center of Mass & Centroid Analysis System',
                'report_generated_on': 'Generated',
                'report_engineer': 'Engineer',
                'report_image_error': 'Preview image could not be rendered',
            },
            'Persian': {
                'title': 'سیستم تحلیل مرکز جرم و مرکز سطح',
                'subtitle': 'پلتفرم تحلیل هندسه دوبعدی و سه بعدی',
                'welcome': 'به سیستم تحلیل مرکز جرم خوش آمدید',
                '2d_analysis': 'تحلیل دوبعدی',
                '3d_analysis': 'تحلیل سه بعدی',
                'stl_import': 'وارد کردن فایل STL',
                'report_generator': 'تولید گزارش',
                'settings': 'تنظیمات',
                'calculate': 'محاسبه',
                'reset': 'بازنشانی',
                'export_pdf': 'خروجی PDF',
                'export_csv': 'خروجی CSV',
                'quick_start_guide': 'راهنمای شروع سریع',
                'quick_start_steps': '''
                    1. **نوع تحلیل را انتخاب کنید**: تحلیل دوبعدی یا سه بعدی را از نوار کناری انتخاب کنید
                    2. **ورود هندسه**: ابعاد را وارد کنید یا فایل وارد کنید
                    3. **محاسبه**: روی محاسبه کلیک کنید تا نتایج را ببینید
                    4. **نمایش تصویری**: با نمایش سه بعدی تعاملی کار کنید
                    5. **خروجی**: گزارش PDF تولید کنید یا داده‌ها را خروجی بگیرید
                ''',
                'btn_2d_title': '🔷\n\n**تحلیل دوبعدی**',
                'btn_2d_desc': 'محاسبه مرکز سطح برای اشکال دوبعدی',
                'btn_2d_list': '• فرمول‌های تحلیلی\n• اشکال ترکیبی\n• ورود مختصات\n• محاسبه مساحت',
                'btn_3d_title': '🔶\n\n**تحلیل سه بعدی**',
                'btn_3d_desc': 'محاسبه مرکز جرم برای اجسام سه بعدی',
                'btn_3d_list': '• مکعب، کره، استوانه\n• اجسام ترکیبی\n• محاسبه حجم\n• نمایش سه بعدی',
                'btn_stl_title': '🔧\n\n**وارد کردن STL**',
                'btn_stl_desc': 'وارد کردن و تحلیل هندسه‌های مش سه بعدی',
                'btn_stl_list': '• پردازش مش\n• انتگرال‌گیری حجم\n• محاسبه مرکز سطح\n• آمار مش',
                # Navigation
                'nav_home': 'خانه',
                'nav_2d': 'تحلیل دوبعدی',
                'nav_3d': 'تحلیل سه بعدی',
                'nav_stl': 'وارد کردن STL',
                'nav_report': 'تولید گزارش',
                'nav_settings': 'تنظیمات',
                'nav_label': 'ناوبری',
                # Theme & Language
                'theme': 'پوسته',
                'theme_dark': 'تاریک',
                'theme_light': 'روشن',
                'theme_system': 'سیستم',
                'language_label': 'زبان / Language',
                'lang_english': 'انگلیسی',
                'lang_persian': 'فارسی',
                # Input modes
                'input_mode': 'حالت ورودی',
                'simple_shapes': 'اشکال ساده',
                'composite_geometry': 'هندسه ترکیبی',
                'coordinate_input': 'ورود مختصات',
                # Shape types
                'shape_type': 'نوع شکل',
                'rectangle': 'مستطیل',
                'circle': 'دایره',
                'triangle': 'مثلث',
                'polygon': 'چندضلعی',
                'cube': 'مکعب',
                'box': 'جعبه',
                'sphere': 'کره',
                'cylinder': 'استوانه',
                'cone': 'مخروط',
                'pyramid': 'هرم',
                # Dimensions
                'width': 'عرض',
                'height': 'ارتفاع',
                'length': 'طول',
                'radius': 'شعاع',
                'base': 'قاعده',
                'base_length': 'طول قاعده',
                'base_width': 'عرض قاعده',
                'base_radius': 'شعاع قاعده',
                'center_x': 'مرکز X',
                'center_y': 'مرکز Y',
                'position_x': 'موقعیت X',
                'position_y': 'موقعیت Y',
                'position_z': 'موقعیت Z',
                # Operations
                'operation': 'عملیات',
                'add_material': '🟢 افزودن ماده',
                'cut_hole': '🔴 برش حفره',
                'add_component': '➕ افزودن جزء',
                'add_3d_component': '➕ افزودن جزء سه بعدی',
                'add_btn': '➕ افزودن',
                'cut_btn': '🔴 برش',
                # Composite
                'composite_shape_builder': 'سازنده شکل ترکیبی',
                'composite_3d_builder': 'سازنده سه بعدی ترکیبی',
                'components_table': 'جدول اجزا',
                'components_3d_table': 'جدول اجزای سه بعدی',
                'click_to_select': 'برای انتخاب روی یک ردیف کلیک کنید، سپس حذف را بزنید:',
                'delete_selected': '🗑️ حذف انتخاب شده',
                'selected_info': 'انتخاب شده',
                'current_components': 'اجزای فعلی',
                'remove': 'حذف',
                # Preview & Results
                'live_preview': 'پیش‌نمایش زنده',
                'live_preview_3d': 'پیش‌نمایش زنده (ترکیبی سه بعدی)',
                'area': 'مساحت',
                'volume': 'حجم',
                'net_area': 'مساحت خالص',
                'net_volume': 'حجم خالص',
                'centroid_x': 'مرکز سطح X',
                'centroid_y': 'مرکز سطح Y',
                'centroid_z': 'مرکز جرم Z',
                'total_area': 'مساحت کل',
                # Stability
                'stability_analysis': 'تحلیل پایداری',
                'stability': 'پایداری',
                'stable': 'پایدار',
                'potentially_unstable': 'احتمالاً ناپایدار',
                'stability_status': 'وضعیت پایداری',
                'centroid_height': 'ارتفاع مرکز جرم',
                'stability_stable_msg': 'مرکز جرم در محدوده تکیه‌گاه قرار دارد که نشان‌دهنده پایداری است.',
                'stability_unstable_msg': 'مرکز جرم بالا ممکن است باعث ناپایداری شود.',
                # Polygon input
                'polygon_coordinate_input': 'ورود مختصات چندضلعی',
                'input_method': 'روش ورود',
                'manual_entry': 'ورود دستی',
                'csv_upload': 'بارگذاری CSV',
                'enter_coordinates': 'مختصات را وارد کنید (هر خط: x,y)',
                'invalid_coordinate': 'فرمت مختصات نامعتبر است',
                'need_3_coordinates': 'لطفاً حداقل ۳ مختصات وارد کنید',
                'upload_csv': 'بارگذاری فایل CSV',
                # STL
                'upload_stl': 'بارگذاری فایل STL',
                'vertices': 'رئوس',
                'faces': 'وجه‌ها',
                'error_stl': 'خطا در پردازش فایل STL',
                # Buttons
                'save_to_report': '💾 ذخیره در گزارش',
                'generate_report': 'تولید گزارش',
                'download_pdf': 'دانلود PDF',
                'download_json': 'دانلود JSON',
                'download_csv': 'دانلود CSV',
                'reset_shape': '🔄 بازنشانی شکل',
                'reset_all': '🔄 بازنشانی همه',
                'reset_btn': '🔄 بازنشانی',
                'save_settings': 'ذخیره تنظیمات',
                # Report Generator
                'analysis_available': 'داده‌های تحلیل برای تولید گزارش موجود است',
                'no_analysis_data': 'داده‌های تحلیلی موجود نیست. لطفاً ابتدا یک تحلیل انجام دهید.',
                'preview_image_label': 'تصویر پیش‌نمایش (در گزارش قرار می‌گیرد)',
                'project_name': 'نام پروژه',
                'engineer_name': 'نام مهندس',
                'additional_notes': 'یادداشت‌های اضافی',
                'report_format': 'فرمت گزارش',
                'generating_report': 'در حال تولید گزارش...',
                'results_saved': 'نتایج ذخیره شد! به بخش تولید گزارش بروید.',
                'settings_saved': 'تنظیمات با موفقیت ذخیره شد!',
                # Settings
                'unit_system': 'سیستم واحد',
                'length_unit': 'واحد طول',
                'precision': 'دقت',
                'decimal_places': 'تعداد اعشار',
                'visualization_settings': 'تنظیمات نمایش',
                'show_grid': 'نمایش شبکه',
                'show_axes': 'نمایش محورها',
                'marker_size': 'اندازه نشانگر',
                # Units
                'mm': 'میلی‌متر',
                'cm': 'سانتی‌متر',
                'm': 'متر',
                'in': 'اینچ',
                'mm2': 'میلی‌متر مربع',
                'mm3': 'میلی‌متر مکعب',
                # Report PDF labels
                'report_title': 'پیش‌نمایش هندسه',
                'report_analysis_results': 'نتایج تحلیل',
                'report_parameter': 'پارامتر',
                'report_value': 'مقدار',
                'report_unit': 'واحد',
                'report_notes': 'یادداشت‌های اضافی',
                'report_generated_by': 'تولید شده توسط سیستم تحلیل مرکز جرم و مرکز سطح',
                'report_generated_on': 'تاریخ تولید',
                'report_engineer': 'مهندس',
                'report_image_error': 'تصویر پیش‌نمایش قابل نمایش نیست',
            }
        }
    
    def get_translations(self, language: str) -> dict:
        """Get translations for a language"""
        return self.translations.get(language, self.translations['English'])